Repository microsoftgraph/microsoft-graph-toolkit, pull requests merged in 2020-06, with the labels that each got.

#446 Updated SPFx sample to 1.3 preview and tested with 1.3
  samples/sp-webpart/README.md
  samples/sp-webpart/config/package-solution.json
  samples/sp-webpart/package.json
  samples/sp-webpart/src/webparts/mgtDemo/components/MgtDemo.tsx
Labels: 1.3

#459 Fixed error handling when setting personDetails on MgtPersonCard
  src/components/mgt-person/mgt-person.ts
Labels: 1.3

#460 Adding setBindingSyntax and globalContext for templates
  samples/examples/template-set-binding-expression.html
  src/components/templateHelper.ts
  src/index.ts
Labels: 1.3

#464 Fixed error handling when setting personImage on MgtPerson
  src/components/mgt-person/mgt-person.ts
Labels: 1.3

#461 people-picker bugs
  src/components/mgt-people-picker/mgt-people-picker.scss
  src/components/mgt-people-picker/mgt-people-picker.ts
Labels: 1.3

#478 mgt-people-picker updating cssprops to match implementation and documentation
  src/components/mgt-people-picker/mgt-people-picker.scss
  src/components/mgt-people-picker/mgt-people-picker.ts
Labels: 1.3, Component: people-picker

#480 adding handling for left and right arrow key events in search
  src/components/mgt-people-picker/mgt-people-picker.ts
Labels: 1.3

#483 Removed unnecessary margin from people-picker
  src/components/mgt-people-picker/mgt-people-picker.scss
Labels: 1.3

#481 update react sample to 1.3 and mgt-react
  samples/react-app/package.json
  samples/react-app/src/App.js
Labels: 1.3

#482 Fixed Agenda not loading on Edge classic
  src/components/mgt-agenda/mgt-agenda.ts
Labels: 1.3

#477 People picker default search state for Groups and groupId
  src/components/mgt-people-picker/mgt-people-picker.ts
  src/graph/graph.groups.ts
  src/graph/graph.people.ts
  stories/components/peoplePicker.stories.js
Labels: 1.3

#486 fix for backspace infinite loading, and refresh people-list upon deletion
  src/components/mgt-people-picker/mgt-people-picker.ts
Labels: 1.3, Component: people-picker

#488 Fix bug for channel picker again :D
  src/components/mgt-people-picker/mgt-people-picker.scss
  src/components/mgt-people-picker/mgt-people-picker.ts
  src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.scss
  src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
Labels: 1.3

#487 people-picker behavior on focus and selection
  src/components/mgt-people-picker/mgt-people-picker.scss
  src/components/mgt-people-picker/mgt-people-picker.ts
Labels: 1.3, Component: people-picker

#491 people-picker teams-channel-picker ie11
  src/components/mgt-people-picker/mgt-people-picker.scss
  src/components/mgt-people-picker/mgt-people-picker.ts
  src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.scss
Labels: 1.3

#485 Update to version 1.3.0
  package.json
  samples/react-app/package.json
  samples/sp-webpart/package.json
  src/utils/version.ts
Labels: 1.3

#494 mgt-teams-channel-picker changes event to @keyup for input change
  src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
Labels: 1.3.1, bug

#497 Fixed bug where msal options are not passed to msal in the TeamsProvider
  src/providers/TeamsProvider.ts
Labels: 1.3.1

#501 handling picker y-overflow in ie11
  src/components/mgt-people-picker/mgt-people-picker.scss
Labels: 1.3.1

#507 teams-channel-picker dropdown scrolling
  src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.scss
  src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
Labels: 1.3.1, Component: teams-channel-picker

#508 Updated msal 1.3.2
  package.json
Labels: 1.3.1

#510 Authority mgtteamsprovider simon
  src/components/providers/mgt-teams-provider.ts
Labels: 1.3.1

#514 polyfills and config necessary for SPFx ie11 support
  samples/sp-webpart/gulpfile.js
  samples/sp-webpart/package.json
  samples/sp-webpart/src/webparts/mgtDemo/MgtDemoWebPart.ts
Labels: 1.3.1

#517 storybook code editor auto indent
  .storybook/addons/codeEditorAddon/editor.js
Labels: mgt.dev
