Repository microsoftgraph/microsoft-graph-toolkit, pull requests merged in 2020-11, with the labels that each got.

#676 Add dark theme to mgt-people-picker and mgt-channel-picker
  packages/mgt-react/src/generated/react.ts
  packages/mgt/src/components/mgt-agenda/mgt-agenda.ts
  packages/mgt/src/components/mgt-login/mgt-login.ts
  packages/mgt/src/components/mgt-people-picker/mgt-people-picker.scss
  packages/mgt/src/components/mgt-people-picker/mgt-people-picker.theme.scss
  packages/mgt/src/components/mgt-people-picker/mgt-people-picker.ts
  packages/mgt/src/components/mgt-people/mgt-people.ts
  packages/mgt/src/components/mgt-person/mgt-person.ts
  packages/mgt/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.scss
  packages/mgt/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.theme.scss
  packages/mgt/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
  packages/mgt/src/styles/shared-styles.scss
  packages/mgt/src/styles/style-helper.ts
  packages/mgt/src/styles/theme.scss
  stories/components/peoplePicker.stories.js
  stories/components/teamsChannelPicker.stories.js
Labels: 2.0, Area: Components, Component: people-picker, breaking changes

#710 Person - added support for a 3rd line
  packages/mgt-react/src/generated/react.ts
  packages/mgt/src/components/mgt-person-card/mgt-person-card.scss
  packages/mgt/src/components/mgt-person-card/mgt-person-card.ts
  packages/mgt/src/components/mgt-person/mgt-person.scss
  packages/mgt/src/components/mgt-person/mgt-person.ts
  stories/components/person.stories.js
Labels: breaking changes

#619 accessibility: localization & rtl
  .storybook/addons/localizeAddon/localizationAddon.js
  .storybook/main.js
  packages/mgt-element/src/components/baseComponent.ts
  packages/mgt-element/src/index.ts
  packages/mgt-element/src/utils/LocalizationHelper.ts
  packages/mgt-react/src/generated/react.ts
  packages/mgt/src/components/mgt-agenda/mgt-agenda.scss
  packages/mgt/src/components/mgt-agenda/mgt-agenda.ts
  packages/mgt/src/components/mgt-login/mgt-login.scss
  packages/mgt/src/components/mgt-login/mgt-login.ts
  packages/mgt/src/components/mgt-login/strings.ts
  packages/mgt/src/components/mgt-people-picker/mgt-people-picker.scss
  packages/mgt/src/components/mgt-people-picker/mgt-people-picker.ts
  packages/mgt/src/components/mgt-people-picker/strings.ts
  packages/mgt/src/components/mgt-person/mgt-person.scss
  packages/mgt/src/components/mgt-person/mgt-person.ts
  packages/mgt/src/components/mgt-tasks-base/mgt-tasks-base.scss
  packages/mgt/src/components/mgt-tasks-base/mgt-tasks-base.ts
  packages/mgt/src/components/mgt-tasks-base/strings.ts
  packages/mgt/src/components/mgt-tasks/mgt-tasks.scss
  packages/mgt/src/components/mgt-tasks/mgt-tasks.ts
  packages/mgt/src/components/mgt-tasks/strings.ts
  packages/mgt/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.scss
  packages/mgt/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
  packages/mgt/src/components/mgt-teams-channel-picker/strings.ts
  packages/mgt/src/components/mgt-todo/mgt-todo.ts
  packages/mgt/src/components/mgt-todo/strings.ts
  packages/mgt/src/components/sub-components/mgt-arrow-options/mgt-arrow-options.scss
  packages/mgt/src/components/sub-components/mgt-dot-options/mgt-dot-options.scss
  packages/mgt/src/components/sub-components/mgt-flyout/mgt-flyout.ts
  stories/samples/general.stories.js
Labels: 2.0

#751 Exposed getInitials and getColorFromName as protected from MgtPerson
  packages/mgt/src/components/mgt-person/mgt-person.ts
Labels: community-contribution

#754 [mgt-agenda] Adding the reload functionality
  packages/mgt/src/components/mgt-agenda/mgt-agenda.ts
Labels: community-contribution

#741 Added mgt-people-picker support for filtering group members when using group-id
  packages/mgt-react/src/generated/react.ts
  packages/mgt/src/components/mgt-people-picker/mgt-people-picker.ts
  packages/mgt/src/components/mgt-people/mgt-people.ts
  packages/mgt/src/graph/graph.groups.ts
  packages/mgt/src/graph/graph.people.ts
  packages/mgt/src/graph/graph.user.ts
  stories/components/peoplePicker.stories.js
Labels: community-contribution

#770 updating highlight search text
  packages/mgt/src/components/mgt-people-picker/mgt-people-picker.scss
Labels: Component: people-picker
