Repository microsoftgraph/microsoft-graph-toolkit, pull requests merged in 2020-10, with the labels that each got.

#696 [people-picker][bug] fires blur event on selection of person
  packages/mgt/src/components/mgt-people-picker/mgt-people-picker.ts
Labels: patch

#709 Adding getPresenceByUserId on mgt-people
  packages/mgt/src/graph/graph.presence.ts
Labels: community-contribution

#724 Update storybook setup (udpate badge, remove addons)
  .storybook/main.js
  readme.md
Labels: mgt.dev

#722 Update to use default font family in mgt-arrow-option to fix mgt-tasks font
  packages/mgt/src/components/sub-components/mgt-arrow-options/mgt-arrow-options.scss
Labels: Component: tasks

#699 Fixed setting storeAuthStateInCookie in MsalProvider
  packages/mgt/src/providers/MsalProvider.ts
Labels: patch

#706 Fixed issue where person would not update when personQuery and userId properties change
  packages/mgt/src/components/mgt-person/mgt-person.ts
Labels: patch

#697 Fixed mgt-person to only require 'Presence.Read' for current signed in user
  packages/mgt/src/components/mgt-person/mgt-person.ts
  packages/mgt/src/graph/graph.presence.ts
Labels: patch
