Repository microsoftgraph/microsoft-graph-toolkit, pull requests merged in 2021-05, with the labels that each got.

#1136 Re-arrange and update the file stories.
  stories/components/file.stories.js
  stories/components/file/file.a.js
  stories/components/file/file.properties.js
  stories/components/file/file.style.js
  stories/components/file/file.templating.js
Labels: 2.2

#1147 Re-arrange and update the file list stories.
  stories/components/file/file.a.js
  stories/components/fileList.stories.js
  stories/components/fileList/fileList.a.js
  stories/components/fileList/fileList.properties.js
  stories/components/fileList/fileList.style.js
  stories/components/fileList/fileList.templating.js
Labels: 2.2

#1143 separating out the personCard stories
  stories/components/personCard.stories.js
  stories/components/personCard/personCard.a.js
  stories/components/personCard/personCard.properties.js
  stories/components/personCard/personCard.style.js
  stories/components/personCard/personCard.templating.js
Labels: 2.2, Component: person-card

#1155 Re-arrange and update the people-picker stories.
  stories/components/peoplePicker/peoplePicker.a.js
  stories/components/peoplePicker/peoplePicker.properties.js
  stories/components/peoplePicker/peoplePicker.style.js
  stories/components/peoplePicker/peoplePicker.templating.js
Labels: 2.2

#1158 Bugfix for mgt-person fallback details
  packages/mgt-components/src/components/mgt-person/mgt-person.ts
Labels: 2.2

#1159 [teams-channel-picker] 2.2 stories structure update
  stories/components/teamsChannelPicker/teamsChannelPicker.a.js
  stories/components/teamsChannelPicker/teamsChannelPicker.style.js
  stories/components/teamsChannelPicker/teamsChannelPicker.templating.js
Labels: 2.2, Component: teams-channel-picker

#1137 Update react package to wc-react 0.5.0 and added ref support
  packages/mgt-react/package.json
  packages/mgt-react/src/Mgt.ts
  samples/react-app/package.json
  samples/react-app/src/App.tsx
Labels: 2.2

#1151 Include fix remove highlighted #1140 , included refresh method of FileList #1029
  packages/mgt-components/src/components/mgt-file-list/mgt-file-list.ts
  packages/mgt-components/src/graph/graph.files.ts
  stories/components/fileList/fileList.properties.js
Labels: 2.2

#1165 [mgt-person-card] css custom properties
  packages/mgt-components/src/components/mgt-person-card/mgt-person-card.scss
  packages/mgt-components/src/components/mgt-person-card/mgt-person-card.theme.scss
  packages/mgt-components/src/components/mgt-person-card/mgt-person-card.ts
  packages/mgt-components/src/components/mgt-person/mgt-person.theme.scss
  stories/components/personCard/personCard.a.js
Labels: 2.2

#1170 rtl implementation fix
  stories/components/agenda/agenda.a.js
  stories/components/file/file.a.js
  stories/components/fileList/fileList.a.js
  stories/components/login/login.stories.js
  stories/components/people/people.a.js
  stories/components/person/person.js
Labels: 2.2
