Repository microsoftgraph/microsoft-graph-toolkit, pull requests merged in 2021-12, with the labels that each got.

#1430 [person-card] Update contact links for contrast
  packages/mgt-components/src/components/mgt-person-card/mgt-person-card.scss
Labels: Area: Accessibility, Component: person-card

#1434 [accessibility] storybook
  .storybook/addons/codeEditorAddon/codeAddon.js
  .storybook/manager-head.html
Labels: Area: Accessibility

#1435 [person-card] Removes sections when there's no data
  packages/mgt-components/src/components/mgt-person-card/sections/mgt-person-card-profile/mgt-person-card-profile.ts
Labels: Component: person-card

#1437 [person] non-fluent focus indicator/tabindex for person person-card login, and other iterations
  packages/mgt-components/src/components/mgt-people/mgt-people.ts
  packages/mgt-components/src/components/mgt-person-card/mgt-person-card.scss
  packages/mgt-components/src/components/mgt-person-card/mgt-person-card.ts
  packages/mgt-components/src/components/mgt-person/mgt-person.scss
  packages/mgt-components/src/components/mgt-person/mgt-person.ts
Labels: Area: Accessibility

#1443 Remove duplicated word in the issue template
  .github/ISSUE_TEMPLATE/support-question.md
Labels: community-contribution

#1445 fixes h1 tag styling
  .storybook/manager-head.html
Labels: Area: Accessibility

#1439 Add ac11y support for the people-picker to narrate selected people
  packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.scss
  packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Labels: Area: Accessibility

#1450 [people-picker] fix for selected people focusable area, removing from normal mgt-person
  packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Labels: Area: Accessibility
