Repository microsoftgraph/microsoft-graph-toolkit, pull requests merged in 2021-02, with the labels that each got.

#900 [mgt-person] Add fallback value when no person/user is found in graph
  packages/mgt-components/src/components/mgt-person/mgt-person.ts
  packages/mgt-react/src/generated/react.ts
  stories/components/person.stories.js
Labels: Needs: Documentation, community-contribution

#909 Fixed bug in saving new todo task datetime
  packages/mgt-components/src/components/mgt-todo/mgt-todo.ts
Labels: Component: tasks

#910 Add mgt-file component
  packages/mgt-components/src/components/components.ts
  packages/mgt-components/src/components/mgt-file/mgt-file.scss
  packages/mgt-components/src/components/mgt-file/mgt-file.theme.scss
  packages/mgt-components/src/components/mgt-file/mgt-file.ts
  packages/mgt-components/src/components/mgt-login/mgt-login.ts
  packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
  packages/mgt-components/src/components/mgt-person-card/mgt-person-card.ts
  packages/mgt-components/src/components/mgt-person-card/sections/mgt-person-card-organization/mgt-person-card-organization.ts
  packages/mgt-components/src/components/mgt-person/mgt-person.ts
  packages/mgt-components/src/graph/graph.files.ts
  packages/mgt-components/src/graph/types.ts
  packages/mgt-components/src/styles/fluent-icons.ts
  packages/mgt-components/src/styles/theme.scss
  packages/mgt-react/scripts/generate.js
  packages/mgt-react/src/generated/react.ts
  samples/examples/file.html
  stories/components/file.stories.js
  stories/components/person.stories.js
Labels: Area: Components, Needs: Documentation
