Repository microsoftgraph/microsoft-graph-toolkit, pull requests merged in 2021-01, with the labels that each got.

#838 Cleaned up graph helpers and removed circular dependency
  packages/mgt-components/src/components/mgt-get/mgt-get.ts
  packages/mgt-components/src/components/mgt-login/mgt-login.ts
  packages/mgt-components/src/components/mgt-person-card/mgt-person-card.ts
  packages/mgt-components/src/components/mgt-person/mgt-person.ts
  packages/mgt-components/src/graph/cacheStores.ts
  packages/mgt-components/src/graph/graph.groups.ts
  packages/mgt-components/src/graph/graph.people.ts
  packages/mgt-components/src/graph/graph.photos.ts
  packages/mgt-components/src/graph/graph.presence.ts
  packages/mgt-components/src/graph/graph.user.ts
  packages/mgt-components/src/graph/graph.userWithPhoto.ts
  packages/mgt-element/src/utils/Cache.ts
Labels: 2.0

#860 Mgt-Person: Added fallback method to search /users endpoint
  packages/mgt-components/src/components/mgt-person/mgt-person.ts
Labels: community-contribution

#867 [bug] [mgt-teams-channel-picker] overflow fix
  packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.scss
  packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
Labels: Component: teams-channel-picker

#830 Updated proxy provider samples
  samples/proxy-provider-asp-net-core/appsettings.json
  samples/proxy-provider-asp-net-core/wwwroot/css/site.css
  samples/proxy-provider-asp-net-mvc/graph-tutorial/PrivateSettings.config.example
  samples/proxy-provider-asp-net-mvc/graph-tutorial/TokenStorage/SessionTokenStore.cs
  samples/proxy-provider-asp-net-mvc/graph-tutorial/Views/Home/Index.cshtml
  samples/proxy-provider-asp-net-mvc/graph-tutorial/Views/Shared/_Layout.cshtml
Labels: 2.0

#875 [bug] [mgt-person-card] userid property fix
  packages/mgt-components/src/components/mgt-person-card/mgt-person-card.ts
Labels: Component: person-card

#886 Include consistencylevel header in Proxy
  samples/proxy-provider-asp-net-core/Controllers/ProxyController.cs
Labels: community-contribution

#857 add react html attributes to the component properties
  packages/mgt-react/src/Mgt.ts
Labels: community-contribution
