Repository microsoftgraph/microsoft-graph-toolkit, pull requests merged in 2022-10, with the labels that each got.

#1864 fix: People picker RTL renders, focus and storybook loading errors
  .storybook/addons/codeEditorAddon/editor.js
  packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.scss
  packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Labels: Build: Storybook

#1874 update: links to learn.microsoft.com
  SECURITY.md
  packages/mgt-components/README.md
  packages/mgt-element/README.md
  packages/mgt-react/readme.md
  packages/mgt-spfx/config/package-solution.json
  packages/mgt/README.md
  packages/providers/mgt-electron-provider/README.md
  packages/providers/mgt-msal-provider/README.md
  packages/providers/mgt-msal-provider/src/MsalProvider.ts
  packages/providers/mgt-msal2-provider/README.md
  packages/providers/mgt-proxy-provider/README.md
  packages/providers/mgt-sharepoint-provider/README.md
  packages/providers/mgt-teams-msal2-provider/README.md
  packages/providers/mgt-teams-provider/README.md
  packages/providers/mgt-teamsfx-provider/README.md
  readme.md
  samples/angular-app/README.md
  samples/angular-app/src/app/nav-bar/nav-bar.component.html
  samples/electron-app/README.md
  samples/msal2provider-asp-net-core-sso/Pages/Index.cshtml
  samples/msal2provider-asp-net-core-sso/wwwroot/css/site.css
  samples/proxy-provider-asp-net-core/README.md
  samples/proxy-provider-asp-net-mvc/README.md
  samples/proxy-provider-node/README.md
  samples/sp-webpart/README.md
  samples/teams-sso-node/readme.md
  samples/teams-tab/readme.md
  specs/mgt-picker.md
  stories/feedback.stories.mdx
  stories/overview.stories.mdx
Labels: Build: Storybook

#1877 Fix: People picker deletion
  packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Labels: Hacktoberfest, Build: Storybook

#1879 ci: remove explict token from gh pages deploy
  .github/workflows/pr-storybook.yml
Labels: Build: Storybook

#1865 update: remove overflow focus on people component
  packages/mgt-components/src/components/mgt-people/mgt-people.ts
  stories/components/login/login.stories.js
Labels: Build: Storybook

#1871 update: Add localization of contact card section titles
  packages/mgt-components/src/components/mgt-person-card/sections/mgt-person-card-contact/mgt-person-card-contact.ts
  packages/mgt-components/src/components/mgt-person-card/sections/mgt-person-card-contact/strings.ts
  stories/components/personCard/personCard.a.js
Labels: Build: Storybook

#1903 Removes assumption that local time is aligned with the calendar time. Closes #1886
  packages/mgt-components/src/components/mgt-agenda/mgt-agenda.ts
Labels: Build: Storybook

#1902 update: show the dropdown when you focus on the people picker with tab key
  packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Labels: Build: Storybook

#1911 Next/node16 support
  .github/workflows/next.yml
  .github/workflows/pr-clean-storybook.yml
  .github/workflows/pr-storybook.yml
  .github/workflows/pr.yml
  .github/workflows/push-release.yml
  .github/workflows/push.yml
  .github/workflows/storybook.yml
  gulpfile.js
  package.json
  packages/mgt-react/src/generated/react.ts
Labels: Build: Storybook

#1872 update: Documentation to use the Developer Portal for teams
  samples/teams-sso-node/readme.md
  samples/teams-tab/readme.md
Labels: Area: Documentation
