Repository microsoftgraph/microsoft-graph-toolkit, pull requests merged in 2023-10, with the labels that each got.

#2744 chore: add query for retemplateMetadata story on mgt-person
  stories/components/person/person.templating.stories.js
Labels: Build: Storybook

#2667 fix(a11y): mgt-file and mgt-picker visibility issues in dark-mode
  packages/mgt-components/src/components/mgt-file-list/mgt-file-list.scss
  packages/mgt-components/src/components/mgt-file-list/mgt-file-list.theme.scss
  packages/mgt-components/src/components/mgt-file/mgt-file.scss
  packages/mgt-components/src/components/mgt-file/mgt-file.theme.scss
  packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.theme.scss
  packages/mgt-components/src/components/mgt-picker/mgt-picker.scss
  packages/mgt-components/src/components/mgt-picker/mgt-picker.theme.scss
Labels: Build: Storybook

#2747 fix: update mgt-taxonomy-picker colors to match mgt-picker
  packages/mgt-components/src/components/mgt-taxonomy-picker/mgt-taxonomy-picker.scss
  packages/mgt-components/src/components/mgt-taxonomy-picker/mgt-taxonomy-picker.theme.scss
  packages/mgt-components/src/components/mgt-taxonomy-picker/mgt-taxonomy-picker.ts
Labels: Build: Storybook

#2745 fix: disable todo checkboxes and inputs in read-only mode
  packages/mgt-components/src/components/mgt-todo/mgt-todo.scss
  packages/mgt-components/src/components/mgt-todo/mgt-todo.ts
Labels: Build: Storybook

#2749 docs: fix icon for storybook site
  .storybook/main.js
  .storybook/manager-head.html
  assets/favicon.ico
  package.json
Labels: Build: Storybook

#2764 fix: initials rendering in mgt-person
  packages/mgt-components/src/components/mgt-person/mgt-person.tests.ts
  packages/mgt-components/src/components/mgt-person/mgt-person.ts
  stories/components/person/person.properties.stories.js
Labels: Build: Storybook, Build: React Contoso

#2766 feat: cache messages received via web sockets
  packages/mgt-chat/src/statefulClient/Caching/MessageCache.ts
  packages/mgt-chat/src/statefulClient/StatefulGraphChatClient.ts
Labels: Build: React Contoso

#2770 fix: show the person card of a sender when you hover on the avatar
  packages/mgt-chat/src/components/Chat/Chat.tsx
Labels: Build: React Contoso

#2771 fix: flyout vertical positioning
  packages/mgt-components/src/components/sub-components/mgt-flyout/mgt-flyout.ts
  packages/mgt-element/src/utils/version.ts
Labels: Build: Storybook

#2786 fix: remove the fallback-details override of person-query
  packages/mgt-components/src/components/mgt-person/mgt-person.ts
  stories/components/person/person.properties.stories.js
Labels: Build: Storybook

#2792 fix: enable the input control when selectedPeople is cleared via code.
  packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
  stories/components/peoplePicker/peoplePicker.properties.stories.js
Labels: Build: Storybook, Build: React Contoso

#2812 feat!: add show-presence to mgt-people-picker
  packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
  packages/mgt-react/src/generated/people-picker.ts
  stories/components/peoplePicker/peoplePicker.properties.stories.js
Labels: Build: Storybook, Build: React Contoso
