Repository microsoftgraph/microsoft-graph-toolkit, pull requests merged in 2023-11, with the labels that each got.

#2822 fix: remove double filtering in mgt-people-picker people filters
  packages/mgt-components/src/graph/graph.people.ts
  stories/components/peoplePicker/peoplePicker.properties.stories.js
Labels: Build: Storybook, Build: React Contoso

#2826 fix: add space to filters template string in people-filters
  packages/mgt-components/src/graph/graph.people.ts
Labels: Needs: Author Feedback, Build: Storybook

#2832 fix: display of flyout hidden by dialog
  samples/react-contoso/src/pages/ChatPage.tsx
Labels: Build: React Contoso

#2841 fix: mgt-chat now has peer deps including react 18
  packages/mgt-chat/package.json
  yarn.lock
Labels: Build: Storybook, Build: React Contoso

#2817 fix: presence icons for dark forced colors
  packages/mgt-components/src/components/mgt-person/mgt-person.scss
Labels: Build: Storybook

#2840 feat!: split config and permission methods out of mgt-person-card
  packages/mgt-components/src/components/components.ts
  packages/mgt-components/src/components/mgt-person-card/MgtPersonCardConfig.ts
  packages/mgt-components/src/components/mgt-person-card/getMgtPersonCardScopes.tests.ts
  packages/mgt-components/src/components/mgt-person-card/getMgtPersonCardScopes.ts
  packages/mgt-components/src/components/mgt-person-card/mgt-person-card.graph.ts
  packages/mgt-components/src/components/mgt-person-card/mgt-person-card.ts
  packages/mgt-components/src/components/mgt-person-card/mgt-person-card.types.ts
  samples/react-contoso/src/index.tsx
Labels: Build: Storybook, Build: React Contoso

#2849 fix: presence fallback logic
  packages/mgt-components/src/components/mgt-person/mgt-person.ts
Labels: Build: Storybook, Build: React Contoso

#2823 fix: update dimensions of the chat component
  packages/mgt-chat/src/components/Chat/Chat.tsx
  packages/mgt-chat/src/components/ChatHeader/ChatTitle.tsx
  packages/mgt-chat/src/components/ChatHeader/useCommonHeaderStyles.tsx
  packages/mgt-chat/src/components/ManageChatMembers/ManageChatMembers.tsx
Labels: Build: React Contoso

#2838 chore: updating the chat list component for performance and design
  samples/react-contoso/package.json
  samples/react-contoso/src/pages/ChatPage.tsx
  samples/react-contoso/src/pages/Chats/ChatItem.tsx
  samples/react-contoso/src/pages/Chats/ChatListTemplate.tsx
  yarn.lock
Labels: Build: React Contoso

#2859 fix: add loop components as unsupported content types
  packages/mgt-chat/src/statefulClient/StatefulGraphChatClient.ts
Labels: Build: React Contoso

#2862 fix: sessionId management
  packages/mgt-chat/src/statefulClient/GraphNotificationClient.ts
  packages/mgt-chat/src/statefulClient/useGraphChatClient.ts
Labels: Build: React Contoso

#2864 fix: subscription caching
  packages/mgt-chat/src/statefulClient/Caching/SubscriptionCache.ts
  packages/mgt-element/src/utils/CacheStore.ts
  packages/mgt-element/src/utils/CustomElement.ts
Labels: Build: React Contoso

#2865 fix: add method to clear selected channel in mgt-teams-channel-picker
  packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
  stories/components/teamsChannelPicker/teamsChannelPicker.stories.js
Labels: Build: Storybook, Build: React Contoso

#2879 fix: set the initial message to an empty string in text area
  packages/mgt-chat/src/components/NewChat/NewChat.tsx
Labels: Build: React Contoso

#2881 fix: set the text size for NewChat to a global default value
  packages/mgt-chat/src/components/NewChat/NewChat.tsx
Labels: Build: React Contoso

#2877 fix: differentiate between me mentions and other user mentions
  packages/mgt-chat/src/components/Chat/Chat.tsx
  packages/mgt-chat/src/utils/mentions.tsx
Labels: Build: React Contoso

#2888 docs: fix person-card sections component names in localization
  packages/mgt-components/src/components/mgt-contact/mgt-contact.ts
  packages/mgt-components/src/components/mgt-contact/strings.ts
  stories/components/personCard/personCard.stories.js
  stories/samples/general.stories.js
Labels: Build: Storybook
