Repository microsoftgraph/microsoft-graph-toolkit, pull requests merged in 2024-06, with the labels that each got.

#3193 fix: tab behavior on person while closing person-card
  packages/mgt-components/src/components/mgt-person-card/mgt-person-card.ts
  packages/mgt-components/src/components/mgt-person/mgt-person.ts
  stories/components/person/person.html.stories.js
Labels: Area: Accessibility, Build: Storybook

#3205 chore: wrap file/folder paths in package.json files in double quotes
  package.json
  packages/mgt-components/package.json
  packages/mgt-element/package.json
  packages/mgt-spfx-utils/package.json
  packages/mgt/package.json
  packages/providers/mgt-electron-provider/package.json
  packages/providers/mgt-mock-provider/package.json
  packages/providers/mgt-msal2-provider/package.json
  packages/providers/mgt-proxy-provider/package.json
  packages/providers/mgt-sharepoint-provider/package.json
  packages/providers/mgt-teamsfx-provider/package.json
Labels: Build: Storybook

#3209 chore: update actions versions
  .github/workflows/next.yml
  .github/workflows/pr-clean-deployments.yml
  .github/workflows/pr-storybook.yml
  .github/workflows/pr-test-app.yml
  .github/workflows/pr.yml
  .github/workflows/push-preview-release.yml
  .github/workflows/push-release.yml
  .github/workflows/push.yml
  .github/workflows/run-release-please.yml
Labels: Build: Storybook, Build: React Contoso

#3214 fix: mgt-planner task deletion on keyboard interaction
  packages/mgt-components/src/components/mgt-planner/mgt-planner.ts
Labels: Area: Accessibility, Build: Storybook

#3220 fix(a11y): correctly narrate tab status in storybook editor
  .storybook/addons/codeEditorAddon/editor.js
Labels: Area: Accessibility, Build: Storybook

#3213 fix(a11y): add stackblitz button styling for high contrast theming
  .storybook/addons/codeEditorAddon/editor.js
Labels: Area: Accessibility, Build: Storybook

#3223 fix: storybook overview component links
  stories/overview.stories.mdx
  stories/samples/general.html.stories.js
Labels: Build: Storybook

#3239 docs: add global person-card config story
  stories/components/personCard/personCard.properties.stories.js
Labels: Build: Storybook

#3237 fix: display only available person-card contact icons on mgt-person-card
  packages/mgt-components/src/components/mgt-person-card/mgt-person-card.ts
Labels: Build: Storybook
