Repository microsoftgraph/microsoft-graph-toolkit, pull requests merged in 2024-05, with the labels that each got.

#3174 fix(a11y): correct person-card contact icons hover style accessibility contrast
  stories/components/personCard/personCard.style.stories.js
Labels: Build: Storybook

#3175 fix(a11y): correct people-picker placeholder luminosity contrast
  stories/components/peoplePicker/peoplePicker.style.stories.js
Labels: Build: Storybook

#3176 fix(a11y): correct mgt-person-card line-3 text color contrast in custom styles
  stories/components/personCard/personCard.style.stories.js
Labels: Build: Storybook

#3177 fix(a11y): correct file upload button and file line-1 color contrast in mgt-file-list
  stories/components/fileList/fileList.style.stories.js
Labels: Build: Storybook

#3185 fix: mgt-channel-picker icons tab behavior
  packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
Labels: Build: Storybook

#3191 fix(a11y): alert files reloaded on mgt-file-list
  stories/components/fileList/fileList.properties.stories.js
Labels: Area: Accessibility, Build: Storybook

#3192 fix: keyboard focus behavior on modal interactions in mgt-people-picker story
  stories/components/peoplePicker/peoplePicker.properties.stories.js
Labels: Area: Accessibility, Build: Storybook

#3188 fix(a11y): set the title and aria-label for the screen sizing buttons
  .storybook/manager.js
Labels: Area: Accessibility, Build: Storybook

#3189 fix(a11y): focus on uploaded file and narrate status
  packages/mgt-components/src/components/mgt-file-list/mgt-file-upload/mgt-file-upload.scss
  packages/mgt-components/src/components/mgt-file-list/mgt-file-upload/mgt-file-upload.ts
  packages/mgt-components/src/components/mgt-file-list/mgt-file-upload/strings.ts
Labels: Area: Accessibility, Build: Storybook

#3186 fix(a11y): announce expanded/collapsed state of options menu in mgt-planner
  packages/mgt-components/src/components/sub-components/mgt-dot-options/mgt-dot-options.scss
  packages/mgt-components/src/components/sub-components/mgt-dot-options/mgt-dot-options.theme.scss
  packages/mgt-components/src/components/sub-components/mgt-dot-options/mgt-dot-options.ts
  packages/mgt-components/src/utils/SvgHelper.ts
  stories/components/planner/planner.style.stories.js
Labels: Area: Accessibility, Build: Storybook

#3194 fix(a11y): correct mgt-get email story
  stories/components/get/get.html.stories.js
Labels: Area: Accessibility, Build: Storybook

#3195 fix(a11y): use descriptive alt text for file icon in mgt-file
  packages/mgt-components/src/components/mgt-file/mgt-file.ts
Labels: Area: Accessibility, Build: Storybook

#3180 fix(a11y): announce when no matches are found in people-picker
  packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Labels: Area: Accessibility, Build: Storybook

#3154 chore(main): release 4.2.2
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending
