Repository microsoftgraph/microsoft-graph-toolkit, pull requests merged in 2024-02, with the labels that each got.

#2994 fix: add focus on input field when you click the button to add a new task
  packages/mgt-components/src/components/mgt-planner/mgt-planner.ts
Labels: Build: Storybook

#3008 fix: clean-up react-contoso homepage
  samples/react-contoso/src/pages/HomePage.tsx
Labels: Build: React Contoso

#3010 fix: make clear cache button adopt theming
  stories/samples/general.stories.js
Labels: Build: Storybook

#2999 fix: add detail-line part attribute to person component
  packages/mgt-components/src/components/mgt-person/mgt-person.tests.ts
  packages/mgt-components/src/components/mgt-person/mgt-person.ts
  stories/components/person/person.style.stories.js
Labels: Build: Storybook, Build: React Contoso

#3005 fix: focus on the input when you cancel adding a todo
  packages/mgt-components/src/components/mgt-todo/mgt-todo.ts
Labels: Build: Storybook

#2996 fix: set add button to disabled until task name is provided
  packages/mgt-components/src/components/mgt-planner/mgt-planner.ts
  stories/samples/general.stories.js
Labels: Build: Storybook

#3018 fix: correct completion of todo items
  packages/mgt-components/src/components/mgt-todo/mgt-todo.ts
Labels: Build: Storybook

#3023 docs: update view usages
  stories/components/person/person.docs.stories.js
  stories/components/person/person.properties.stories.js
Labels: Build: Storybook

#3011 fix: apply keyboard focus when removing selected person or adding person from suggestion list on people-picker
  packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Labels: Build: Storybook

#3020 chore(main): release 4.0.1
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3054 docs: fix contrast ratio on overview page
  .storybook/preview.css
  packages/mgt-element/src/utils/version.ts
Labels: Build: Storybook

#3048 feat: add ability to disable suggestions on people-picker
  packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
  stories/components/peoplePicker/peoplePicker.properties.stories.js
Labels: Build: Storybook

#3044 chore(main): release 4.1.0
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3102 fix: add key to mentions
  packages/mgt-chat/src/utils/mentions.tsx
Labels: Build: React Contoso
